### ISSUE TITLE
[BUG] have you tried it with small region high resolution images 

### ISSUE THREAD

**Issue by sumanttyagi** [LADI-Dataset/ladi-overview#12]
- [ ] my doubt is let's say there are 30 house only 1 is damage is this model performance robust  or if you write some improvement areas where still development is needed
- [ ] let's say rather than resizing it if i clip the images and try to classify does the performance improve ?

**Comment by sscheele** [comment]
Thanks for your interest in our models! We do not have plans to fix performance issues of this type, but additional performance statistics are always welcome and could be useful to people trying to deploy this model in real life. I'm closing this issue, but please feel free to respond if you find anything of interest here. 

In response to your questions: anecdotally, images containing a combination of damaged and undamaged houses seem to have good performance for our models, but we do not have solid data for this and the dataset doesn't have a good way to get it (we don't have labels for detection or instance segmentation).

**Comment by jeffliu-LL** [comment]
We have not formally evaluated this, but it would be worthwhile to experiment on running the classifier on cropped regions of the original image and aggregating the results together. This may be helpful for some of the images from higher altitudes or in denser urban areas.
