### ISSUE TITLE
[ANNOTATION] add the csv file which include filenames for test train split with labels

### ISSUE THREAD

**Issue by sumanttyagi** [LADI-Dataset/ladi-overview#13]
Downloading an entire dataset can be resource-intensive and inefficient. Instead, having a CSV file with predefined training and test splits offers significant advantages. This CSV file can be used for various purposes, such as fine-tuning models, maintaining consistent splits across experiments, and evaluating performance on unseen data. Moreover, it allows users to easily validate and compare the results of different models or algorithms without the need to repeatedly split the dataset. This approach not only saves resources but also ensures consistency and reproducibility in machine learning workflows.

Please upload the csv file.!!!

**Comment by sscheele** [comment]
From the README:

```
You can also manually access the dataset at https://ladi.s3.amazonaws.com/index.html, or via AWS S3 at s3://ladi, and the provided dataset class in training/LADI-v2-dataset
```

The CSV files are in the S3 bucket.
