### ISSUE TITLE
[ENHANCEMENT] can you release the weights of  all the models

### ISSUE THREAD

**Issue by sumanttyagi** [LADI-Dataset/ladi-overview#14]
Please release the weights of all the models :v2, v2a, v2_resized, v2a_resized, v1_damage, and v1_infra.
as it would act has pre trained weight for finetuning or transfer learning for similar projects in this area

**Comment by sscheele** [comment]
From the README:

Pretrained Classifiers

We provide a set of pretrained classifiers on the LADI v2 dataset for downstream finetuning and deployment purposes. See the associated model cards on Hugging Face for instructions on how to use.

    [LADI-v2-classifier-small](https://huggingface.co/MITLL/LADI-v2-classifier-small) - Recommended for deployment, based on [google/bit-50](https://huggingface.co/google/bit-50), trained on entire LADI v2 dataset
    [LADI-v2-classifier-large](https://huggingface.co/MITLL/LADI-v2-classifier-large) - Based on [microsoft/swinv2](https://huggingface.co/microsoft/swinv2-large-patch4-window12to16-192to256-22kto1k-ft), trained on entire LADI v2 dataset

We also provide "reference" versions of each model which are trained only on the train split of the LADI v2 dataset, to aid in reproducing the results presented in the paper.

    [LADI-v2-classifier-small-reference](https://huggingface.co/MITLL/LADI-v2-classifier-small)
    [LADI-v2-classifier-large-reference](https://huggingface.co/MITLL/LADI-v2-classifier-large-reference)
